Liters/role led
IntelligentRoboticsLab/dnt-hulk pull request #119
Opened 2023-07-07 20:01 UTC by Lasse-van-Iterson

## Introduced Changes

The NAO's will now change their eye color based on their currently assigned role

Fixes #117 

## Ideas for Next Iterations (Not This PR)

- New colors (more easily viewable)

## How to Test

Run code on NAO and force roles using twix

2023-07-07 20:02 UTC, oxkitsune commented
good stuff guys! will take a look

2023-07-07 20:05 UTC, oxkitsune requested changes

2023-07-07 20:05 UTC, oxkitsune commented on crates/control/src/led_status.rs
> +                    Role::DefenderLeft | Role::DefenderRight => Eye::defender_eye(),
Could we maybe split this up, and split the colours in the eye based on the defender side? Might be useful!

2023-07-07 20:19 UTC, Fyor requested changes
Looks good, but I would like to have a guide/wiki where I can see the mapping from role to eye color.

2023-07-07 20:19 UTC, Fyor commented on crates/control/src/led_status.rs
> +                    Role::ReplacementKeeper => Eye::keeper_replacement_eye(),
```suggestion
                    Role::ReplacementKeeper => Eye::replacement_keeper_eye(),
```

2023-07-07 20:19 UTC, Fyor commented on crates/types/src/led.rs
> +    pub fn keeper_replacement_eye() -> Eye {
```suggestion
    pub fn replacement_keeper_eye() -> Eye {
```

2023-07-07 20:45 UTC, Redjeepkaiser commented on crates/types/src/led.rs
> +            color_at_0: Rgb::new(255, 0, 0),
User Rgb::Red

2023-07-07 20:45 UTC, Redjeepkaiser commented on crates/types/src/led.rs
> +            color_at_0: Rgb::new(255, 255, 255),
Use rgb::white.

2023-07-07 20:46 UTC, Redjeepkaiser commented on crates/types/src/led.rs
> +            color_at_0: Rgb::new(0, 0, 255),
See comments above

2023-07-07 20:46 UTC, Redjeepkaiser requested changes
Looks good!

2023-07-08 10:32 UTC, oxkitsune approved these changes

2023-07-08 10:32 UTC, merged